/* Generated by tools/build-plan-data.mjs — edit that, not this. */
/* Demo data. Invented names only: this file is public. */
window.DEFAULT_PLAN = {
  "name": "Example plan",
  "guests": [
    {
      "id": "g-1",
      "first": "Ada",
      "last": "Bell",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-2",
      "first": "Ben",
      "last": "Bell",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-3",
      "first": "Cleo",
      "last": "Fox",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-4",
      "first": "Dan",
      "last": "Fox",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-5",
      "first": "Elsie",
      "last": "Hart",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-6",
      "first": "Femi",
      "last": "Hart",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-7",
      "first": "Greta",
      "last": "Lane",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-8",
      "first": "Hugo",
      "last": "Lane",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-9",
      "first": "Iris",
      "last": "Moss",
      "diet": "vegetarian",
      "allergy": null
    },
    {
      "id": "g-10",
      "first": "Jonah",
      "last": "Moss",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-11",
      "first": "Kit",
      "last": "Nolan",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-12",
      "first": "Lena",
      "last": "Nolan",
      "diet": null,
      "allergy": "Peanuts"
    },
    {
      "id": "g-13",
      "first": "Mira",
      "last": "Okafor",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-14",
      "first": "Nils",
      "last": "Okafor",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-15",
      "first": "Omar",
      "last": "Pike",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-16",
      "first": "Pia",
      "last": "Pike",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-17",
      "first": "Quinn",
      "last": "Reid",
      "diet": "vegan",
      "allergy": null
    },
    {
      "id": "g-18",
      "first": "Rosa",
      "last": "Reid",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-19",
      "first": "Sam",
      "last": "Shaw",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-20",
      "first": "Tara",
      "last": "Shaw",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-21",
      "first": "Umar",
      "last": "Tate",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-22",
      "first": "Vera",
      "last": "Tate",
      "diet": "pescatarian",
      "allergy": null
    },
    {
      "id": "g-23",
      "first": "Will",
      "last": "Vance",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-24",
      "first": "Xena",
      "last": "Vance",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-25",
      "first": "Yuri",
      "last": "Ward",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-26",
      "first": "Zoe",
      "last": "Ward",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-27",
      "first": "Anya",
      "last": "Bright",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-28",
      "first": "Bo",
      "last": "Bright",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-29",
      "first": "Cara",
      "last": "Doyle",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-30",
      "first": "Dev",
      "last": "Doyle",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-31",
      "first": "Effie",
      "last": "Ellis",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-32",
      "first": "Frank",
      "last": "Ellis",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-33",
      "first": "Gia",
      "last": "Gale",
      "diet": null,
      "allergy": null
    },
    {
      "id": "g-34",
      "first": "Hal",
      "last": "Gale",
      "diet": null,
      "allergy": null
    }
  ],
  "tables": [
    {
      "id": "t-top-table",
      "name": "Top table",
      "kind": "rect",
      "x": 700,
      "y": 260,
      "angle": 0,
      "seats": 6
    },
    {
      "id": "t-rosemary",
      "name": "Rosemary",
      "kind": "diamond",
      "x": 380,
      "y": 720,
      "angle": 0,
      "sides": {
        "ne": 2,
        "se": 3,
        "sw": 2,
        "nw": 3
      }
    },
    {
      "id": "t-juniper",
      "name": "Juniper",
      "kind": "diamond",
      "x": 1020,
      "y": 720,
      "angle": 0,
      "sides": {
        "ne": 2,
        "se": 3,
        "sw": 2,
        "nw": 3
      }
    },
    {
      "id": "t-thyme",
      "name": "Thyme",
      "kind": "diamond",
      "x": 700,
      "y": 1160,
      "angle": 0,
      "sides": {
        "ne": 2,
        "se": 3,
        "sw": 2,
        "nw": 3
      }
    }
  ],
  "seating": {
    "t-top-table": [
      "g-1",
      "g-2",
      "g-3",
      "g-4",
      "g-5",
      "g-6"
    ],
    "t-rosemary": [
      "g-7",
      "g-8",
      "g-9",
      "g-10",
      "g-11",
      "g-12",
      "g-13",
      "g-14",
      "g-15",
      "g-16"
    ],
    "t-juniper": [
      "g-17",
      "g-18",
      "g-19",
      "g-20",
      "g-21",
      "g-22",
      "g-23",
      "g-24",
      "g-25",
      "g-26"
    ],
    "t-thyme": [
      "g-27",
      "g-28",
      "g-29",
      "g-30",
      "g-31",
      null,
      "g-32",
      "g-33",
      "g-34",
      null
    ]
  }
};
